[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/storopoli/ciencia-de-dados/main?filepath=notebooks%2FAula_12_Regressao_Logistica.ipynb)
<br>
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/storopoli/ciencia-de-dados/blob/main/notebooks/Aula_12_Regressao_Logistica.ipynb)

# Regressão Logística

**Objetivos**: Aprender o que é Regressão Logística e Regressão Softmax usando a biblioteca `Scikit-Learn`. Introduzir o aluno aos problemas de classificação de aprendizagem de máquina.

## Definição - Regressão Logística

> Uma regressão logística se comporta exatamente como um modelo linear: faz uma predição simplesmente computando uma soma ponderada dos atributos (*features*), mais uma constante chamada viés (*bias*), também chamado de constante (*intercept*). Porém ao invés de retornar um valor contínuo, como a regressão linear, retorna a função logística desse valor.

$$\operatorname{Logística}(x) = \frac{1}{1 + e^{(-x)}}$$

In [2]:
import pandas as pd
df = pd.read_csv("/content/sick (1).data")
df.head()

,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,query hypothyroid,...,TT4 measured,TT4,T4U measured,T4U,FTI measured,FTI,TBG measured,TBG,referral source,sick negative
0,41,F,f,f,f,f,f,f,f,f,...,t,125,t,1.14,t,109,f,?,SVHC,negative.|3733
1,23,F,f,f,f,f,f,f,f,f,...,t,102,f,?,f,?,f,?,other,negative.|1442
2,46,M,f,f,f,f,f,f,f,f,...,t,109,t,0.91,t,120,f,?,other,negative.|2965
3,70,F,t,f,f,f,f,f,f,f,...,t,175,f,?,f,?,f,?,other,negative.|806
4,70,F,f,f,f,f,f,f,f,f,...,t,61,t,0.87,t,70,f,?,SVI,negative.|2807

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        2800 non-null   object
 1   sex                        2800 non-null   object
 2   on thyroxine               2800 non-null   object
 3   query on thyroxine         2800 non-null   object
 4   on antithyroid medication  2800 non-null   object
 5   sick                       2800 non-null   object
 6   pregnant                   2800 non-null   object
 7   thyroid surgery            2800 non-null   object
 8   I131 treatment             2800 non-null   object
 9   query hypothyroid          2800 non-null   object
 10  query hyperthyroid         2800 non-null   object
 11  lithium                    2800 non-null   object
 12  goitre                     2800 non-null   object
 13  tumor                      2800 non-null   object
 14  hypopituitary              2800 non-null   object
 15  psych                      2800 non-null   object
 16  TSH measured               2800 non-null   object
 17  TSH                        2800 non-null   object
 18  T3 measured                2800 non-null   object
 19  T3                         2800 non-null   object
 20  TT4 measured               2800 non-null   object
 21  TT4                        2800 non-null   object
 22  T4U measured               2800 non-null   object
 23  T4U                        2800 non-null   object
 24  FTI measured               2800 non-null   object
 25  FTI                        2800 non-null   object
 26  TBG measured               2800 non-null   object
 27  TBG                        2800 non-null   object
 28  referral source            2800 non-null   object
 29  sick negative              2800 non-null   object
dtypes: object(30)
memory usage: 656.4+ KB

In [4]:
df[['target', 'score']] = df['sick negative'].str.split('.', expand=True)

In [5]:
df.head()

,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,query hypothyroid,...,T4U measured,T4U,FTI measured,FTI,TBG measured,TBG,referral source,sick negative,target,score
0,41,F,f,f,f,f,f,f,f,f,...,t,1.14,t,109,f,?,SVHC,negative.|3733,negative,|3733
1,23,F,f,f,f,f,f,f,f,f,...,f,?,f,?,f,?,other,negative.|1442,negative,|1442
2,46,M,f,f,f,f,f,f,f,f,...,t,0.91,t,120,f,?,other,negative.|2965,negative,|2965
3,70,F,t,f,f,f,f,f,f,f,...,f,?,f,?,f,?,other,negative.|806,negative,|806
4,70,F,f,f,f,f,f,f,f,f,...,t,0.87,t,70,f,?,SVI,negative.|2807,negative,|2807

In [6]:
df = df.drop(["sick negative","score"] ,axis=1)
df.head()

,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,query hypothyroid,...,TT4 measured,TT4,T4U measured,T4U,FTI measured,FTI,TBG measured,TBG,referral source,target
0,41,F,f,f,f,f,f,f,f,f,...,t,125,t,1.14,t,109,f,?,SVHC,negative
1,23,F,f,f,f,f,f,f,f,f,...,t,102,f,?,f,?,f,?,other,negative
2,46,M,f,f,f,f,f,f,f,f,...,t,109,t,0.91,t,120,f,?,other,negative
3,70,F,t,f,f,f,f,f,f,f,...,t,175,f,?,f,?,f,?,other,negative
4,70,F,f,f,f,f,f,f,f,f,...,t,61,t,0.87,t,70,f,?,SVI,negative

In [7]:
df["age"].unique()

array(['41', '23', '46', '70', '18', '59', '80', '66', '68', '84', '67',
       '71', '28', '65', '42', '63', '51', '81', '54', '55', '60', '25',
       '73', '34', '78', '37', '85', '26', '58', '64', '44', '48', '61',
       '35', '83', '21', '87', '53', '77', '27', '69', '74', '38', '76',
       '45', '36', '22', '43', '72', '82', '31', '39', '49', '62', '57',
       '1', '50', '30', '29', '75', '19', '7', '79', '17', '24', '15',
       '32', '47', '16', '52', '33', '13', '10', '89', '56', '20', '90',
       '40', '88', '14', '86', '94', '12', '4', '11', '8', '5', '455',
       '2', '91', '6', '?', '93', '92'], dtype=object)

In [8]:
df.groupby('age')['age'].count()

age
1     6
10    1
11    2
12    2
13    7
     ..
91    2
92    1
93    1
94    2
?     1
Name: age, Length: 94, dtype: int64

In [9]:
df = df.loc[(df['age'] != '?')
                       &
                       (df['age'] != '455')]

In [ ]:
## print out the rows that contain missing values.
## Valores estranhos '?', 455
df.loc[(df['age'] == '455')]

,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,query hypothyroid,...,TT4 measured,TT4,T4U measured,T4U,FTI measured,FTI,TBG measured,TBG,referral source,sick negative
1364,455,F,f,f,f,f,f,f,f,f,...,t,118,t,1.13,t,104,f,?,SVI,negative.|861

In [ ]:
df["sex"].unique()

array(['F', 'M', '?'], dtype=object)

In [ ]:
df.groupby('sex')['sex'].count()

sex
?     110
F    1830
M     860
Name: sex, dtype: int64

In [10]:
df = df.loc[(df['sex'] != '?')]

In [ ]:
## print out the rows that contain missing values.
## Valores estranhos '?', 455
df.loc[(df['sex'] == '?')]

In [ ]:
df["on thyroxine"].unique()

array(['f', 't'], dtype=object)

In [ ]:
df.groupby('on thyroxine')['on thyroxine'].count()

on thyroxine
f    2367
t     321
Name: on thyroxine, dtype: int64

In [ ]:
df["query on thyroxine"].unique()

array(['f', 't'], dtype=object)

In [ ]:
df.groupby("query on thyroxine")["query on thyroxine"].count()

query on thyroxine
f    2648
t      40
Name: query on thyroxine, dtype: int64

In [11]:
df = df.drop('query on thyroxine', axis=1)

In [ ]:
df["on antithyroid medication"].unique()

array(['f', 't'], dtype=object)

In [ ]:
df.groupby("on antithyroid medication")["on antithyroid medication"].count()

on antithyroid medication
f    2654
t      34
Name: on antithyroid medication, dtype: int64

In [ ]:
df["sick"].unique()

array(['f', 't'], dtype=object)

In [ ]:
df.groupby("sick")["sick"].count()

sick
f    2580
t     108
Name: sick, dtype: int64

In [ ]:
df["pregnant"].unique()

array(['f', 't'], dtype=object)

In [ ]:
df.groupby("pregnant")["pregnant"].count()

pregnant
f    2648
t      40
Name: pregnant, dtype: int64

In [ ]:
df["thyroid surgery"].unique()

array(['f', 't'], dtype=object)

In [ ]:
df.groupby("thyroid surgery")["thyroid surgery"].count()

thyroid surgery
f    2649
t      39
Name: thyroid surgery, dtype: int64

In [ ]:
df["I131 treatment"].unique()

array(['f', 't'], dtype=object)

In [ ]:
df.groupby("I131 treatment")["I131 treatment"].count()

I131 treatment
f    2644
t      44
Name: I131 treatment, dtype: int64

In [ ]:
df["query hypothyroid"].unique()

array(['f', 't'], dtype=object)

In [ ]:
df.groupby("query hypothyroid")["query hypothyroid"].count()

query hypothyroid
f    2528
t     160
Name: query hypothyroid, dtype: int64

In [12]:
df = df.drop('query hypothyroid', axis=1)

In [ ]:
df["query hyperthyroid"].unique()

array(['f', 't'], dtype=object)

In [ ]:
df.groupby("query hyperthyroid")["query hyperthyroid"].count()

query hyperthyroid
f    2520
t     168
Name: query hyperthyroid, dtype: int64

In [13]:
df = df.drop('query hyperthyroid', axis=1)

In [ ]:
df["lithium"].unique()

array(['f', 't'], dtype=object)

In [ ]:
df.groupby("lithium")["lithium"].count()

lithium
f    2674
t      14
Name: lithium, dtype: int64

In [ ]:
df["goitre"].unique()

array(['f', 't'], dtype=object)

In [ ]:
df.groupby("goitre")["goitre"].count()

goitre
f    2663
t      25
Name: goitre, dtype: int64

In [ ]:
df["tumor"].unique()

array(['f', 't'], dtype=object)

In [ ]:
df.groupby("tumor")["tumor"].count()

tumor
f    2618
t      70
Name: tumor, dtype: int64

In [ ]:
df["hypopituitary"].unique()

array(['f', 't'], dtype=object)

In [ ]:
df.groupby("hypopituitary")["hypopituitary"].count()

hypopituitary
f    2687
t       1
Name: hypopituitary, dtype: int64

In [ ]:
df["psych"].unique()

array(['f', 't'], dtype=object)

In [ ]:
df.groupby("psych")["psych"].count()

psych
f    2554
t     134
Name: psych, dtype: int64

In [ ]:
df["TSH measured"].unique()

array(['t', 'f'], dtype=object)

In [ ]:
df.groupby("TSH measured")["TSH measured"].count()

TSH measured
t    2417
Name: TSH measured, dtype: int64

In [14]:
df = df.loc[(df['TSH measured'] != 'f')]

In [ ]:
df["TSH"].unique()

array(['1.3', '4.1', '0.98', '0.16', '0.72', '0.03', '?', '2.2', '0.6',
       '2.4', '1.1', '2.8', '3.3', '12', '1.5', '6', '2.1', '0.1', '0.8',
       '1.9', '3.1', '0.2', '13', '0.3', '0.035', '2.5', '0.5', '1.7',
       '7.3', '1.8', '0.26', '45', '5.4', '0.99', '0.25', '0.92', '0.15',
       '0.64', '1', '0.4', '2', '2.6', '14.8', '15', '19', '3', '3.2',
       '1.6', '0.005', '0.31', '0.61', '0.05', '160', '0.025', '4.3',
       '1.4', '151', '0.04', '3.9', '0.02', '9.4', '7.8', '2.7', '2.3',
       '0.94', '0.045', '3.5', '0.88', '0.01', '0.08', '4.5', '0.68',
       '0.7', '27', '1.2', '6.1', '0.75', '0.55', '26', '5.2', '0.77',
       '0.07', '0.9', '11.4', '143', '0.45', '0.57', '0.65', '0.015',
       '16', '108', '9', '0.83', '9.2', '2.9', '86', '0.62', '0.59',
       '9.1', '5.9', '52', '0.33', '31', '0.28', '51', '6.3', '4.4',
       '9.6', '3.4', '0.09', '24', '0.76', '42', '25', '10', '4.6', '8.6',
       '0.66', '6.2', '0.79', '0.86', '9.7', '0.84', '28', '17', '18',
       '55', '14', '3.7', '6.7', '0.74', '7.6', '0.065', '0.29', '0.37',
       '8', '11', '0.48', '44', '7.9', '5', '7.2', '0.89', '0.93', '0.97',
       '0.12', '6.4', '33', '0.85', '7.1', '0.73', '199', '8.2', '188',
       '0.22', '98', '6.6', '5.1', '0.06', '0.42', '3.8', '35', '4',
       '0.78', '0.63', '0.52', '60', '0.43', '0.87', '5.6', '6.9', '22',
       '3.6', '29', '0.38', '4.9', '0.41', '9.9', '7.5', '34', '6.5',
       '4.7', '103', '0.95', '0.35', '4.2', '0.67', '0.81', '0.54',
       '0.58', '8.9', '5.5', '0.34', '9.3', '0.13', '54', '0.39', '8.3',
       '478', '21', '6.8', '0.32', '0.23', '0.24', '8.1', '0.91', '5.3',
       '100', '0.27', '1.01', '58', '41', '183', '18.4', '0.47', '0.17',
       '0.19', '0.82', '43', '0.44', '70', '7.7', '8.4', '0.69', '8.5',
       '0.21', '82', '0.055', '0.96', '0.71', '38', '0.36', '9.8', '7',
       '0.46', '11.1', '39', '76', '5.7', '32', '126', '5.8', '26.4',
       '0.53', '0.49', '178', '145', '47', '36', '8.8', '4.8', '10.3',
       '89', '7.4', '0.51', '116', '0.14', '61', '99', '46', '78', '468'],
      dtype=object)

In [ ]:
df.groupby("TSH")["TSH"].count()

TSH
0.005    42
0.01     15
0.015    18
0.02     40
0.025    10
         ..
9.7       4
9.8       1
9.9       2
98        2
99        1
Name: TSH, Length: 261, dtype: int64

In [ ]:
df["T3 measured"].unique()

array(['t', 'f'], dtype=object)

In [ ]:
df.groupby("T3 measured")["T3 measured"].count()

T3 measured
t    2053
Name: T3 measured, dtype: int64

In [15]:
df = df.loc[(df['T3 measured'] != 'f')]

In [ ]:
df["T3"].unique()

array(['2.5', '2', '1.9', '1.2', '0.6', '2.2', '1.6', '3.8', '1.7', '1.8',
       '2.6', '2.1', '0.3', '5.5', '1.4', '3.1', '1.5', '2.3', '2.4',
       '2.7', '0.9', '1', '2.9', '0.8', '1.3', '0.4', '3.5', '3.4', '1.1',
       '2.8', '4.2', '3.7', '3', '0.7', '4.8', '4.3', '0.05', '3.2',
       '5.4', '4', '0.5', '0.2', '3.3', '5.2', '3.6', '6', '5', '5.3',
       '3.9', '4.6', '4.5', '7.3', '4.7', '6.7', '4.1', '0.1', '4.9',
       '10.6', '5.1', '7', '6.2', '4.4', '7.1'], dtype=object)

In [ ]:
df.groupby("T3")["T3"].count()

T3
0.05     2
0.1      2
0.2     11
0.3     16
0.4     15
        ..
6.2      1
6.7      1
7        1
7.1      1
7.3      1
Name: T3, Length: 63, dtype: int64

In [ ]:
df["TT4 measured"].unique()

array(['t', 'f'], dtype=object)

In [ ]:
df.groupby("TT4 measured")["TT4 measured"].count()

TT4 measured
t    2049
Name: TT4 measured, dtype: int64

In [16]:
df = df.loc[(df['TT4 measured'] != 'f')]

In [ ]:
df["TT4"].unique()

In [ ]:
df.groupby("TT4")["TT4"].count()

TT4
10       3
100     32
101     62
102     39
103     47
      ...
96      42
97      33
98      47
99      41
?      184
Name: TT4, Length: 218, dtype: int64

In [ ]:
df["T4U measured"].unique()

array(['t', 'f'], dtype=object)

In [ ]:
df.groupby("T4U measured")["T4U measured"].count()

T4U measured
t    1946
Name: T4U measured, dtype: int64

In [17]:
df = df.loc[(df['T4U measured'] != 'f')]

In [ ]:
df["T4U"].unique()

In [ ]:
df.groupby("T4U")["T4U"].count()

T4U
0.31    1
0.41    1
0.48    1
0.49    1
0.5     1
       ..
1.88    1
1.93    1
1.94    1
2.03    1
2.12    1
Name: T4U, Length: 135, dtype: int64

In [ ]:
df["FTI measured"].unique()

array(['t'], dtype=object)

In [ ]:
df.groupby("FTI measured")["FTI measured"].count()

FTI measured
t    1946
Name: FTI measured, dtype: int64

In [ ]:
df["FTI"].unique()

In [ ]:
df.groupby("FTI")["FTI"].count()

FTI
10      4
100    40
101    37
102    30
103    29
       ..
95     24
96     42
97     36
98     37
99     27
Name: FTI, Length: 196, dtype: int64

In [ ]:
df["TBG measured"].unique()

array(['f'], dtype=object)

In [ ]:
df.groupby("TBG measured")["TBG measured"].count()

TBG measured
f    1946
Name: TBG measured, dtype: int64

In [18]:
df = df.drop(["TBG measured","TBG"], axis = 1 )

In [ ]:
df["TBG"].unique()

array([], dtype=object)

In [ ]:
df.groupby("TBG")["TBG"].count()

Series([], Name: TBG, dtype: int64)

In [ ]:
df["TBG"].unique()

array([], dtype=object)

In [ ]:
df["TBG"]

Series([], Name: TBG, dtype: object)

In [ ]:
df.groupby("TBG")["TBG"].count()

In [ ]:
df["referral source"].unique()

array(['SVHC', 'SVI', 'other', 'SVHD', 'STMW'], dtype=object)

In [ ]:
df.groupby("referral source")["referral source"].count()

referral source
STMW      70
SVHC     261
SVHD      28
SVI      695
other    892
Name: referral source, dtype: int64

In [ ]:
df["referral source"].unique()

array(['SVHC', 'SVI', 'other', 'SVHD', 'STMW'], dtype=object)

In [ ]:
df["target"].unique()

array(['negative', 'sick'], dtype=object)

In [ ]:
df.groupby("target")["target"].count()

target
negative    1788
sick         158
Name: target, dtype: int64

In [19]:
df = df.drop("referral source", axis = 1)

In [20]:
df = df.drop(["TSH measured", "T3 measured", "TT4 measured",
             "T4U measured", "FTI measured"],  axis = 1)

In [ ]:
158/(1788+158)*100

8.119218910585817

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1946 entries, 0 to 2799
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        1946 non-null   float64
 1   sex                        1946 non-null   object
 2   on thyroxine               1946 non-null   object
 3   on antithyroid medication  1946 non-null   object
 4   sick                       1946 non-null   object
 5   pregnant                   1946 non-null   object
 6   thyroid surgery            1946 non-null   object
 7   I131 treatment             1946 non-null   object
 8   lithium                    1946 non-null   object
 9   goitre                     1946 non-null   object
 10  tumor                      1946 non-null   object
 11  hypopituitary              1946 non-null   object
 12  psych                      1946 non-null   object
 13  TSH                        1946 non-null   object
 14  T3                         1946 non-null   object
 15  TT4                        1946 non-null   object
 16  T4U                        1946 non-null   object
 17  FTI                        1946 non-null   object
 18  target                     1946 non-null   object
dtypes: float64(1), object(18)
memory usage: 304.1+ KB

In [21]:
df['age'] = df['age'].astype(float)
df['TSH'] = df['TSH'].astype(float)
df['T3'] = df['T3'].astype(float)
df['TT4'] = df['TT4'].astype(float)
df['T4U'] = df['T4U'].astype(float)
df['FTI'] = df['FTI'].astype(float)

In [22]:
df

,age,sex,on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,lithium,goitre,tumor,hypopituitary,psych,TSH,T3,TT4,T4U,FTI,target
0,41.0,F,f,f,f,f,f,f,f,f,f,f,f,1.30,2.5,125.0,1.14,109.0,negative
4,70.0,F,f,f,f,f,f,f,f,f,f,f,f,0.72,1.2,61.0,0.87,70.0,negative
7,80.0,F,f,f,f,f,f,f,f,f,f,f,f,2.20,0.6,80.0,0.70,115.0,sick
8,66.0,F,f,f,f,f,f,f,f,f,t,f,f,0.60,2.2,123.0,0.93,132.0,negative
9,68.0,M,f,f,f,f,f,f,f,f,f,f,f,2.40,1.6,83.0,0.89,93.0,negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2788,70.0,M,f,f,f,f,f,f,f,f,f,f,f,1.50,1.5,70.0,0.77,91.0,negative
2790,67.0,M,f,f,f,f,f,f,f,f,f,f,f,2.10,2.0,83.0,0.96,87.0,negative
2793,82.0,F,f,f,f,f,f,f,f,f,f,f,f,0.03,1.4,74.0,0.52,143.0,negative
2794,25.0,F,f,f,f,f,f,f,f,f,f,f,f,1.90,1.7,167.0,1.21,137.0,negative
2799,81.0,F,f,f,f,f,f,f,f,f,f,f,f,1.20,1.5,114.0,0.99,115.0,negative

In [23]:
df = df.reset_index(drop=True)

In [24]:
X = df.drop('target', axis = 1)
y = df['target']

In [25]:
y_sick = y == 'sick' # get the index for each non-zero value in y
y[y_sick] = 1  # set each non-zero value in y to 1

y_neg = y == 'negative' # get the index for each non-zero value in y
y[y_neg] = 0  # set each non-zero value in y to 0

y = y.astype('int')

<ipython-input-25-0b394cca11f4>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y[y_sick] = 1  # set each non-zero value in y to 1
<ipython-input-25-0b394cca11f4>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y[y_neg] = 0  # set each non-zero value in y to 0

In [26]:
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 1946 entries, 0 to 1945
Series name: target
Non-Null Count  Dtype
--------------  -----
1946 non-null   int64
dtypes: int64(1)
memory usage: 15.3 KB

In [27]:
X  # DataFrame somente com as colunas de feature_names

,age,sex,on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,lithium,goitre,tumor,hypopituitary,psych,TSH,T3,TT4,T4U,FTI
0,41.0,F,f,f,f,f,f,f,f,f,f,f,f,1.30,2.5,125.0,1.14,109.0
1,70.0,F,f,f,f,f,f,f,f,f,f,f,f,0.72,1.2,61.0,0.87,70.0
2,80.0,F,f,f,f,f,f,f,f,f,f,f,f,2.20,0.6,80.0,0.70,115.0
3,66.0,F,f,f,f,f,f,f,f,f,t,f,f,0.60,2.2,123.0,0.93,132.0
4,68.0,M,f,f,f,f,f,f,f,f,f,f,f,2.40,1.6,83.0,0.89,93.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941,70.0,M,f,f,f,f,f,f,f,f,f,f,f,1.50,1.5,70.0,0.77,91.0
1942,67.0,M,f,f,f,f,f,f,f,f,f,f,f,2.10,2.0,83.0,0.96,87.0
1943,82.0,F,f,f,f,f,f,f,f,f,f,f,f,0.03,1.4,74.0,0.52,143.0
1944,25.0,F,f,f,f,f,f,f,f,f,f,f,f,1.90,1.7,167.0,1.21,137.0
1945,81.0,F,f,f,f,f,f,f,f,f,f,f,f,1.20,1.5,114.0,0.99,115.0

In [28]:
X = X.replace(['f', 't', 'F', 'M'], [0, 1, 0, 1])

In [29]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1946 entries, 0 to 1945
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        1946 non-null   float64
 1   sex                        1946 non-null   int64
 2   on thyroxine               1946 non-null   int64
 3   on antithyroid medication  1946 non-null   int64
 4   sick                       1946 non-null   int64
 5   pregnant                   1946 non-null   int64
 6   thyroid surgery            1946 non-null   int64
 7   I131 treatment             1946 non-null   int64
 8   lithium                    1946 non-null   int64
 9   goitre                     1946 non-null   int64
 10  tumor                      1946 non-null   int64
 11  hypopituitary              1946 non-null   int64
 12  psych                      1946 non-null   int64
 13  TSH                        1946 non-null   float64
 14  T3                         1946 non-null   float64
 15  TT4                        1946 non-null   float64
 16  T4U                        1946 non-null   float64
 17  FTI                        1946 non-null   float64
dtypes: float64(6), int64(12)
memory usage: 273.8 KB

In [30]:
y  # Series da coluna survived

0       0
1       0
2       1
3       0
4       0
       ..
1941    0
1942    0
1943    0
1944    0
1945    0
Name: target, Length: 1946, dtype: int64

### Quebrando dataset em `train` e `test`

Usar a função do Scikit-Learn [`sklearn.model_selection.train_test_split()`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)

#### Argumentos:

* matriz a ser dividida - `X` ou `y`
* `test_size` - `float` ou `int` do tamanho do dataset de teste (padrão $0.25$)
* `train_size` - padrão `1 - test_size`
* `random_state` - `int` - seed do gerador de número randômicos (replicabilidade)

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=123)

In [32]:
print('Tamanho de X_train: ', X_train.shape, '\n')
print('Tamanho de X_test: ', X_test.shape, '\n')
print('Tamanho de y_train: ', y_train.shape, '\n')
print('Tamanho de y_test: ', y_test.shape, '\n')

Tamanho de X_train:  (1459, 18)

Tamanho de X_test:  (487, 18)

Tamanho de y_train:  (1459,)

Tamanho de y_test:  (487,)

### Regressão Logística
Usar a classe do Scikit-Learn [`sklearn.linear_model.LogisticRegression()`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)

#### Argumentos:
* `max_iter` - `int` - Número máximo de iterações do *Gradient Descent*
    * padrão `100`
* `random_state` - `int` - seed do gerador de número randômicos (replicabilidade)
* `n_jobs` - `int` - Número de núcleos de processamento que será utilizado em paralelo
    * `None` - padrão
    * `-1` - usa todos os núcleos

#### Retorna:
* Objeto `estimator` do Scikit-Learn

In [ ]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(n_jobs=-1, random_state=123)

### Classe `Estimators`

* `.fit()` - Treina o Modelo
    * `X`
    * `y`
* `.predict()` - Gera predições do modelo
    * `X`
* `.coef_` - Retorna os coeficientes do modelo ($\theta_i$)
* `.intercept_` - Retorna o viés/constante (*bias/intercept*) do modelo ($\theta_0$)

In [ ]:
clf.fit(X_train, y_train)

LogisticRegression(n_jobs=-1, random_state=123)

In [ ]:
feature_names  = X.columns

In [ ]:
# Coeficientes do modelo
for feature, coef in zip(feature_names, clf.coef_[0].tolist()):
    print(f"{feature}: {round(coef, 3)}")

# Constante do modelo
print(f"Constante: {round(clf.intercept_[0], 3)}")

age: 0.004
sex: 0.147
on thyroxine: -0.436
on antithyroid medication: -0.079
sick: 0.236
pregnant: -0.004
thyroid surgery: -0.313
I131 treatment: 0.212
lithium: -0.047
goitre: -0.14
tumor: 0.148
hypopituitary: 0.57
psych: -0.256
TSH: -0.016
T3: -4.196
TT4: -0.011
T4U: 0.467
FTI: 0.031
Constante: 0.687

### Acurácia do Modelo
Usar a função do Scikit-Learn [`sklearn.metrics.accuracy_score()`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html)

Retorna um score de acurácia `float` entre $0$ e $1$

#### Argumentos
* `y_true`: Classes Verdadeiras
    * 2 classes: vetor (1-D)
    * Mais que 2 classes: matriz (2-D)
* `y_pred`: Classes Previstas pelo Modelo
    * 2 classes: vetor (1-D)
    * Mais que 2 classes: matriz (2-D)

In [ ]:
from sklearn.metrics import accuracy_score

y_train_true = y_train
y_train_pred = clf.predict(X_train)
y_test_true = y_test
y_test_pred = clf.predict(X_test)


print(f"Acurácia de Treino: {round(accuracy_score(y_train_true, y_train_pred), 2)}")
print('\n ---------------------------\n')
print(f"Acurácia de Teste: {round(accuracy_score(y_test_true, y_test_pred), 2)}")
print('\n ---------------------------\n')

Acurácia de Treino: 0.95

 ---------------------------

Acurácia de Teste: 0.95

 ---------------------------

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, auc
import matplotlib.pyplot as plt


y_test_pred = clf.predict(X_test)


# Calcule as métricas de desempenho
acuracia = accuracy_score(y_test, previsoes)
precisao = precision_score(y_test, previsoes)
recall = recall_score(y_test, previsoes)
f1 = f1_score(y_test, previsoes)
roc_auc = roc_auc_score(y_test, previsoes)

# Imprima as métricas
print("Acurácia: {:.2f}".format(acuracia))
print("Precisão: {:.2f}".format(precisao))
print("Recall: {:.2f}".format(recall))
print("F1-Score: {:.2f}".format(f1))
print("Área sob a Curva ROC (AUC-ROC): {:.2f}".format(roc_auc))

# Plote a curva ROC
fpr, tpr, thresholds = roc_curve(y_test, previsoes)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = {:.2f})'.format(roc_auc))
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('Taxa de Falso Positivo')
plt.ylabel('Taxa de Verdadeiro Positivo')
plt.title('Curva ROC')
plt.legend(loc="lower right")
plt.show()

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

ValueError: ignored

## Expandindo para $k$ classes

Podemos usar Regressão Logística para mais de uma duas classes ($k > 2$)

### Função Softmax

Dado um vetor $\mathbf{x}$, a função Softmax computa um score $s_k(\mathbf{x})$ para cada classe $k$, então estima a probabilidade de cada classe.

$$\hat{p}_k = \sigma(\mathbf{s}(\mathbf{x}))_k = \frac{e^{s_k(\mathbf{x})}}{\sum_{j=1}^K e^{s_j(\mathbf{x})}}$$

* $K$ - número de classes
* $\mathbf{s}(\mathbf{x})$ - vetor contendo todos os scores de cada classe de uma observação $x$
* $\sigma(\mathbf{s}(\mathbf{x}))_k$ - a probabilidade estimada ($\hat{p}_k$) que a obsevação $x$ pertence a classe $k$, dado os scores de cada classe para $x$

In [ ]:
# Exemplo para 3 classes
# p_hat = [0.25, 0.50, 0.25]
# y_hat = 2 # indice 2

### Regressão Softmax

Que nem a Regressão Logística, a Regressão Softmax prevê a classe com maior probabilidade estimada (que é simplesmente a classe com o maior score)

$$\hat{y} = \max_k \sigma(\mathbf{s}(\mathbf{x}))_k = \max_k s_k(\mathbf{x})$$

### Regressão Softmax (Regressão Logística Multinomial)
Usar a função do Scikit-Learn [`sklearn.linear_model.Logistic Regression()`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)

Não possui opções de controle da taxa de aprendizagem do Método do Gradiente Descendente

#### Argumentos:
* `multi_class` - `str`
    * `'ovr'` - Binário ($k=2$)
    * `'multinomial'` - Multiclasses ($k > 2$)
    * `'auto'` - se baseia nas dimensões da `array` `y` que é passada no `.fit()`
* `max_iter` - `int` - Número máximo de iterações do *Gradient Descent*
* `tol` - Tolerância - Critério de parada de treino
* `random_state` - `int` - seed do gerador de número randômicos (replicabilidade)

#### Retorna:
* Objeto `estimator` do Scikit-Learn

#### O que muda da Regressão Logística?
Agora o meu $y$ é uma matriz (2-D) e não um vetor (1-D)

### Métrica de Desempenho de uma Regressão Softmax

**Cross Entropy**: Estender a Log Loss para mais que duas classes

$$Cross~Entropy = -\frac{1}{m} \sum_{i=1}^{m} \sum_{k=1}^K y_k^{(i)} \log (\hat{p}_k^{(i)})$$

* $y_k^{(i)}$ é a probabilidade alvo que a observação $i$ pertence à classe $k$. De maneira geral, ou é $1$ ou $0$, dependendo de qual classe $i$ pertence.

## Atividade - Regressão com o dataset [Iris](https://scikit-learn.org/stable/datasets/index.html#iris-dataset)

Edgar Anderson coletou os dados para quantificar a variação morfológica das flores de íris de três espécies relacionadas.

O conjunto de dados consiste em 50 amostras de cada uma das três espécies de Iris (Setosa, Virginica e Versicolor). Quatro características foram medidas em cada amostra (cm):

* $N = 150$
* Atributos: 4
    * `sepal length (cm)` - Cumprimento da Sépala
    * `sepal width (cm)` - Largura da Sépala
    * `petal length (cm)` - Cumprimento da Pétala
    * `petal width (cm)` - Largua da Sépala
* Variável dependente: Tipo de espécie de Iris
    * `0` - Setosa
    * `1` - Virginica
    * `2` - Versicolor

* Achar a acurácia do modelo nos dados de teste e os respectivos coeficientes dos atributos ($\theta_i$) e viés/constante ($\theta_0$)

>Obs: usar `test_size = 0.25` e `random_state = 123`

<img src="https://github.com/storopoli/ciencia-de-dados/blob/main/notebooks/images/iris-species.png?raw=1" alt="iris-sepals-petals" style="width: 600px;"/>

In [ ]:
from sklearn.datasets import load_iris

iris = load_iris()
X = iris['data']
y = iris['target']

In [ ]:
print('Nomes dos Atributos: ', iris['feature_names'], '\n')
print('Tamanho de X: ', X.shape, '\n')
print('Tamanho de y: ', y.shape, '\n')

Nomes dos Atributos:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Tamanho de X:  (150, 4)

Tamanho de y:  (150,)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=123)

In [ ]:
print('Tamanho de X_train: ', X_train.shape, '\n')
print('Tamanho de X_test: ', X_test.shape, '\n')
print('Tamanho de y_train: ', y_train.shape, '\n')
print('Tamanho de y_test: ', y_test.shape, '\n')

Tamanho de X_train:  (112, 4)

Tamanho de X_test:  (38, 4)

Tamanho de y_train:  (112,)

Tamanho de y_test:  (38,)

In [ ]:
from sklearn.linear_model import LogisticRegression